# Final pipeline

## Getting raw files (test set)

In [1]:
!pip install yadisk -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.7/140.7 kB 8.0 MB/s eta 0:00:00

In [2]:
import yadisk
import os
import zipfile

In [3]:
# инициализация клиента и ссылка
yd = yadisk.YaDisk()
public_link = "https://disk.yandex.ru/d/kIlHLgOMYgA7gA"

try:
    # ~ 1-5 минут. размер: ~3,9 гб
    yd.download_public(
        public_link,
        'test_set.zip'
        )
    print('completed')
except Exception as e:
    print(e)

completed

In [4]:
!unzip -q /content/test_set.zip -d /content/test_set

## Dependencies

In [5]:
!pip -q install "stable-ts[fw]"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.1/189.1 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 6.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.8/35.8 MB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.6/39.6 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 3.0 MB/s eta 0:00:00
  Building wheel for openai-whisper (pyproject.toml) ... done
  Building wheel for stable-ts (setup.py) ... done

In [6]:
import torch
import os
import json

import librosa
from stable_whisper import load_faster_whisper

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import re
from datetime import date
from tqdm.notebook import tqdm

from transformers import AutoTokenizer, AutoModel

## Funcs to run

In [7]:
# сгруппировать файлы в подпакеты "оператор-год"
def group_agents_years(file_names: list) -> dict:
    agents_years_dict = {}

    for file_name in file_names:
        timestamp, agent_id = file_name.split('_', 1)

        # номер оператора в формате `_01` (str). так согласовано
        agent_id = agent_id.rsplit('.', 1)[0].\
                  replace('.', '').\
                  removesuffix('_muted').\
                  removeprefix('Оператор')
        year = timestamp[:4]
        agent_id = f'{agent_id.zfill(2)}_{year}'

        # добавляем в словарь
        agents_years_dict[agent_id] = agents_years_dict.setdefault(agent_id, [])
        agents_years_dict[agent_id].append(file_name)

    return agents_years_dict

In [8]:
def get_raw_timeline(model,
                     file_path
                     ) -> list:

    # каналы из файла: 1 = оператор
    # только 16000, не моно; иначе виспер не справится
    y, sr = librosa.load(file_path, sr=16000, mono=False)
    agent_audio = y[1]

    # промпт для адаптации под домен техподдержки с паравербаликой
    tech_support_prompt = (
        "Разговор клиента с оператором техподдержки "
        "(IP-адрес, роутер, интернет, сеть, логин, компьютер, пароли). "
        "Участники вздыхают, запинаются и используют "
        "междометия в речи, например: эээ, ммм, ага, угу, так, ой. "
        "В тексте сохраняются все паузы, вздохи, цифры и термины."
    )
    # параметры сырой транскрибации. подобраны эмпирически
    transcribe_params = dict(
        language='ru',
        initial_prompt=tech_support_prompt,
        suppress_tokens=[-1], # не блокируем токены, чтобы не терять вздохи и др.
        word_timestamps=True, # временные метки слов для расчета метрик
        vad_filter=True,
        vad_parameters=dict(
            min_speech_duration_ms=250, # не менее 250 миллисекунд на реплику
            max_speech_duration_s=15, # есть весьма длинные
            speech_pad_ms=600
            ),
        temperature=[0.0, 0.2, 0.4, 0.6],
        compression_ratio_threshold=2.4,
        no_speech_threshold=0.8 # чтобы отлавливать тихие звуки (уверенность в том, что сегмент не содержит речи, = 0,8, т.е. весьма высокая). артефакты потом чистим регулярками
    )

    # транскрибация из канала оператора
    agent_result = model.transcribe(agent_audio, **transcribe_params)

    # первичный парсинг
    raw_timeline = []
    for seg in agent_result.segments:
        # временные метки при наличии
        words_data = []
        if hasattr(seg, 'words') and seg.words:
            words_data = [{'word': w.word, 'start': w.start, 'end': w.end} for w in seg.words]

        raw_timeline.append({
            'start': seg.start,
            'end': seg.end,
            'text': seg.text.strip(),
            'words': words_data
        })

    # сортировка чанков по временным меткам (с одним спикером уже излишне, скорее всего)
    raw_timeline.sort(key=lambda x: x['start'])

    return raw_timeline, agent_audio

In [9]:
# объединение последовательных реплик спикера, если между ними не более 1,2 секунды
# обычно в русском языке мена ролей в диалоге происходит при паузе от 1 до 1,5 секунды
# в наборе из-за пустот между репликами возможны паузы до нескольких минут
def merge_timeline(raw_timeline,
                   MAX_MERGE_GAP_SEC=1.2 # порог объединения
                   ) -> list:

    merged_timeline = []
    if raw_timeline:
        current = raw_timeline[0]

        for next_seg in raw_timeline[1:]:
            # пауза между сегментами
            gap_between_segments = next_seg['start'] - current['end']

            # сливаем реплики, если пауза не больше порога
            if gap_between_segments <= MAX_MERGE_GAP_SEC:
                current['end'] = next_seg['end']
                current['text'] += " " + next_seg['text']
                current['words'].extend(next_seg['words'])

            # иначе переходим к следующему сегменту
            else:
                merged_timeline.append(current)
                current = next_seg

        merged_timeline.append(current)

    return merged_timeline

In [10]:
# подсчет метрик по реплике
def process_merged_timeline(merged_timeline,
                            agent_audio,
                            text_embedder,
                            ### OPENSMILE_PARSER, ###
                            SPLITTER_MS=400,
                            ) -> pd.DataFrame:
    # фильтрация галлюцинаций транскрибатора. могут быть и другие
    hallucination_pattern = re.compile(
        r'(прис|продолжение\s+следует|субтитры\s+сделал|спасибо\s+за\s+субтитры\s+алексею\s+дубровскому|субтитры\s+создавал|dimatorzok|подписывайтесь\s+на\s+канал|спасибо\s+за\s+просмотр)',
        re.IGNORECASE
        )

    # для сводных аудиодорожек и транскрипций
    rep_arrays_list = []
    rep_texts_list = []

    # для расчета паузации и скорости речи по репликам
    rep_interword_pause_means = []
    rep_speech_rates = []

    rows = []
    for i, rep in enumerate(merged_timeline):
        # очистка от галлюцинаций
        cleaned_text = hallucination_pattern.sub("", rep['text']).strip()
        cleaned_text = re.sub(r'^[\s\.\,\-\?\!]+$', "", cleaned_text).strip()

        if not cleaned_text:
            continue

        # длительность в миллисекундах
        rep_duration_ms = int((rep['end'] - rep['start']) * 1000)
        rep_duration_sec = rep_duration_ms / 1000.0
        rep_word_count = len(cleaned_text.split()) if cleaned_text else 0

        # скорость речи в реплике = слов в секунду. обычно в русском языке 2-3,5 слов в секунду
        rep_speech_rate_wps = round(rep_word_count / rep_duration_sec, 2) if rep_duration_sec > 0 else 0.0
        rep_speech_rates.append(rep_speech_rate_wps)

        # средняя длительность паузы между словами в реплике
        rep_interword_pauses = []
        words = rep['words']
        if words and len(words) > 1:
            for idx in range(len(words) - 1):
                pause = words[idx+1]['start'] - words[idx]['end']
                if pause > 0:
                    rep_interword_pauses.append(pause)
        if rep_interword_pauses:
            rep_interword_pause_means.append(np.mean(rep_interword_pauses))

        # вырезание реплики
        start_idx = int(rep['start'] * 16000)
        end_idx = int(rep['end'] * 16000)
        rep_audio_chunk = agent_audio[start_idx:end_idx]

        # слияние всех реплик
        rep_arrays_list.append(rep_audio_chunk)
        rep_texts_list.append(cleaned_text)

    # сплиттер между фрагментами. аналог в транскрипции представлен как `|`.
    splitter = np.zeros(SPLITTER_MS * int(16000 / 1000), dtype=int)
    agent_result_list = []
    for i, arr in enumerate(rep_arrays_list):
        agent_result_list.append(arr)
        # аналогично join
        if i < len(rep_arrays_list) - 1:
            agent_result_list.append(splitter)

    # сводные аудиодорожка и транскрипция
    # ! канал может быть пустым (не распознано реплик), тогда конкатенация
    # выдаст ValueError. в пайплайне обработано через try/except.
    agent_result_audio = np.concatenate(agent_result_list)
    agent_result_text = ' | '.join(rep_texts_list)

    # пауза между словами. из средних по репликам: среднее + станд. откл.
    avg_interword_pause_ms = int(np.mean(rep_interword_pause_means) * 1000) if rep_interword_pause_means else 0
    std_interword_pause_ms = int(np.std(rep_interword_pause_means) * 1000) if rep_interword_pause_means else 0

    # RMS энергии
    rms_energy = np.sqrt(np.mean(agent_result_audio**2)) if len(agent_result_audio) > 0 else 0

    # от средней скорости речи для каждой реплики: среднее + станд. откл.
    avg_speech_rate_wps = round(np.mean(rep_speech_rates), 2) if rep_speech_rates else 0
    std_speech_rate_wps = round(np.std(rep_speech_rates), 2) if rep_speech_rates else 0

    # количество слов в сводной транскрипции (включая предлоги итд)
    word_count = len(agent_result_text.replace('|', '').split()) if agent_result_text else 0

    # длительность сводной аудиодорожки
    duration_sec = len(agent_result_audio) / 16000

    # средняя скорость речи по сводной аудиодорожке
    acc_speech_rate_wps = round(word_count / duration_sec, 2) if duration_sec > 0 else 0.0

    # первичные признаки
    agent_result_dict = {
        # 'audio': agent_result_audio,
        'text': agent_result_text,
        'word_count': int(word_count),
        'avg_interword_pause_ms': float(avg_interword_pause_ms),
        'std_interword_pause_ms': float(std_interword_pause_ms),
        'avg_speech_rate_wps': float(avg_speech_rate_wps),
        'std_speech_rate_wps': float(std_speech_rate_wps),
        'acc_speech_rate_wps': float(acc_speech_rate_wps),
        'duration_sec': float(duration_sec),
        'rms_energy': float(round(float(rms_energy), 6))
        }

    # эмбеддинги из BERT (по умолчанию -- RoSBERTa, 1024)
    bert_embeddings = text_embedder.extract(agent_result_text)
    bert_feature_names = [f'bert_{i + 1}' for i in range(len(bert_embeddings))]
    bert_dict = dict(zip(bert_feature_names, bert_embeddings))
    agent_result_dict |= bert_dict

    # !! OpenSMILE
    ### OPENSMILE_PARSER.parse(agent_result_audio) ###

    return agent_result_dict

In [11]:
# парсим название файла
def parse_file_path(file_path) -> tuple:
    file_name = file_path.rsplit('/', 1)[-1]
    file_timestamp, agent_id = file_name.split('_', 1)

    # номер оператора в формате `_01` (str). так согласовано
    agent_id = agent_id.rsplit('.', 1)[0].\
               replace('.', '').\
               removesuffix('_muted').\
               removeprefix('Оператор')
    agent_id = f'_{agent_id.zfill(2)}'

    # год, месяц, дата, час записи (int)
    year = int(file_timestamp[:4])
    month = int(file_timestamp[4:6])
    day = int(file_timestamp[6:8])
    hour = int(file_timestamp[8:10])

    # день недели (str)
    weekday = date(int(year), int(month), int(day)).strftime("%a")

    # анные для новых столбцов
    new_cols = (file_name, agent_id, year, month, day, weekday, hour)

    return new_cols

In [12]:
# дополнение словаря
def process_dict(agent_result_dict, file_path):

    # столбцы из старого имени для отладки. ставятся в начало
    new_cols = parse_file_path(file_path)
    ID_dict = dict(zip(
        ['file_name', 'agent_id', 'year', 'month', 'day', 'weekday', 'hour'],
        new_cols)
    )
    new_dict = ID_dict | agent_result_dict

    return new_dict

In [13]:
def predict(row: pd.Series, # строка датафрейма
            JSON_STRING
            ):
    # выгружаем json в словарь
    _secret_dict = JSON_STRING#json.loads(JSON_STRING)

    # предсказываем: свободный член + сумма произведений
    # извлекаем свободный член
    prediction_score = _secret_dict['Intercept']

    # определяем пересечение с присутствующими признаками:
    # ключи словаря & индекс строки
    feature_set = set(_secret_dict.keys()).intersection(row.index)
    # print(len(feature_set))

    for feat in feature_set:
        # забираем вес признака
        weight = _secret_dict[feat]

        # добавляем произведение к свободному члену
        prediction_score += row[feat] * weight

    return prediction_score

In [14]:
def predict_all(agent_year_df,
                json_string_filter,
                json_strings_experts,
                json_string_agent_sex,
                json_string_burnout,
                ):

    filtered_rows = []
    for i, row in agent_year_df.iterrows():
        # предсказание №1 = фильтрация
        # оценить зашумленность/малоинформативность (чем больше, тем хуже)
        filter_score = predict(row, json_string_filter)
        # print(i, filter_score)
        threshold = 0.5

        # оставляем только те, что ниже порога
        if round(filter_score, 8) < threshold:
            # предсказание №2 (серия из 8 признаков) = психолингвистика
            # предсказываем все 8 реконструированных признаков экспертной разметки
            for expert_feat, json_string_expert in json_strings_experts.items():
                row[expert_feat] = predict(row, json_string_expert)

            # добавляем в отфильтрованный набор обогащенную строку
            filtered_rows.append(row)

    # объединение отфильтрованных и обогащенных
    agent_year_df = pd.DataFrame(filtered_rows)

    # предсказание №3. пол
    json_string_agent_sex

    # индекс столбца с текстом + 1, чтобы взять только числовые столбцы после него
    agent_cols = agent_year_df.columns.tolist()
    agent_text_ix = agent_cols.index('text')

    # усреднение по пакету "оператор-год" и предсказание пола
    agent_year_mean = agent_year_df[agent_cols[agent_text_ix + 1:]].mean()
    agent_sex_predicted = predict(agent_year_mean, json_string_agent_sex)
    # бинаризация для дальнейших предсказаний
    agent_sex_predicted = int(round(agent_sex_predicted, 8) > 0.5)

    agent_year_mean['m'] = agent_sex_predicted
    agent_year_mean['f'] = 1 - agent_sex_predicted

    agent_year_df['m'] = agent_sex_predicted
    agent_year_df['f'] = 1 - agent_sex_predicted

    # agent_year_mean['agent_sex'] = agent_sex_predicted
    # agent_year_df['agent_sex'] = agent_sex_predicted

    # предсказание №4. "выгорание"
    json_string_burnout
    # по средним признаков
    agent_burnout_predicted = predict(agent_year_mean, json_string_burnout)
    agent_year_mean['burnout'] = agent_burnout_predicted
    agent_year_df['burnout'] = agent_burnout_predicted
    # бинаризация по порогу 0.5
    agent_year_df['burnout_final'] = (agent_year_df['burnout'].round(8) > 0.5).astype(int)

    # сокращенная версия с предсказаниями; полная -- для интерпретации
    return (agent_year_df[['file_name', 'burnout', 'burnout_final']],
            agent_year_df)

## BERT for text embeddings

In [15]:
class TextEmbedder:
    # по умолчанию -- "ai-forever/ru-en-RoSBERTa" для максимального качества семантики
    # хотя мб хватило бы "cointegrated/rubert-tiny2"
    def __init__(self,
                 model_name="ai-forever/ru-en-RoSBERTa",
                 device="cuda",
                 ):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name).to(device).eval()
        self.embedding_size = self.model.config.hidden_size # 312 для rubert/tiny2, 1024 для RoSBERTa
        self.device = device

    @torch.no_grad()
    def extract(self, text):
        if not isinstance(text, str) or len(text.strip()) == 0:
            return np.zeros(self.embedding_size, dtype=np.float32)

        # Для тяжелых моделей важно установить max_length и truncation
        inputs = self.tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True
        ).to(self.device)

        outputs = self.model(**inputs)

        # Mean pooling по токенам с учетом attention_mask
        token_embeddings = outputs.last_hidden_state
        input_mask_expanded = inputs.attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
        sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)

        return (sum_embeddings / sum_mask).squeeze(0).cpu().numpy()

## Loading models

In [16]:
# проверка GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda

In [17]:
model = load_faster_whisper(
    'large-v3-turbo',
    # 'large-v3',
    device=device,
    compute_type='float16'
    )

In [18]:
text_embedder = TextEmbedder(
    model_name="ai-forever/ru-en-RoSBERTa",
    device=device
    )

config.json:   0%|          | 0.00/715 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.49M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.82M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/5.99M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.61GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: ai-forever/ru-en-RoSBERTa
Key                 | Status  |
--------------------+---------+-
pooler.dense.bias   | MISSING |
pooler.dense.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Inference loop

In [19]:
# подтянуть JSON с коэффициентами

### JSON с коэффициентами из переменных окружения ###
with open('json_string_filter.json', 'r') as f:
    json_string_filter = json.load(f)

with open('json_string_participation_modal_n.json', 'r') as f:
    json_string_participation_modal_n = json.load(f)

with open('json_string_greeting_flg.json', 'r') as f:
    json_string_greeting_flg = json.load(f)

with open('json_string_farewell_flg.json', 'r') as f:
    json_string_farewell_flg = json.load(f)

with open('json_string_etiquette_present_flg.json', 'r') as f:
    json_string_etiquette_present_flg = json.load(f)

with open('json_string_etiquette_absent_flg.json', 'r') as f:
    json_string_etiquette_absent_flg = json.load(f)

with open('json_string_participation_dominant_flg.json', 'r') as f:
    json_string_participation_dominant_flg = json.load(f)

with open('json_string_distancing_dominant_flg.json', 'r') as f:
    json_string_distancing_dominant_flg = json.load(f)

with open('json_string_clarifying_absent_flg.json', 'r') as f:
    json_string_clarifying_absent_flg = json.load(f)

with open('json_string_agent_sex.json', 'r') as f:
    json_string_agent_sex = json.load(f)

with open('json_string_burnout.json', 'r') as f:
    json_string_burnout = json.load(f)


# для экспертной разметки (8 признаков)
json_strings_experts = {
    'participation_modal_n': json_string_participation_modal_n,

    'greeting_flg': json_string_greeting_flg,
    'farewell_flg': json_string_farewell_flg,

    'etiquette_present_flg': json_string_etiquette_present_flg,
    'etiquette_absent_flg': json_string_etiquette_absent_flg,

    'participation_dominant_flg': json_string_participation_dominant_flg,

    'distancing_dominant_flg': json_string_distancing_dominant_flg,
    'clarifying_absent_flg': json_string_clarifying_absent_flg,
}

In [20]:
# откуда берем файлы
input_dir = '/content/test_set'
input_files = os.listdir(input_dir)

file_dicts = []
input_dir

'/content/test_set'

In [21]:
# сгруппировать в подпакеты "оператор-год"
agents_years_dict = group_agents_years(input_files)

# словарь для хранения датафреймов с признаками
agent_years_df_dict = {}

# итерируемся по словарю: сводный ID оператор-год и [все его файлы за этот год]
for agent_year_id, files_to_process in agents_years_dict.items():

    # список для хранения словарей по всем записям для оператор/год
    agent_dicts = []

    # итерируемся по всем файлам этого "оператор-год"
    for i, original_file in enumerate(files_to_process, start=1):
        # путь к файлу
        file_path = os.path.join(
            input_dir,
            original_file
            )
        # для быстрой отладки
        # print(f'Оператор_Год={agent_year_id}: {i}/{len(files_to_process)}. {original_file}'.center(80, '='))

        # пайплайн
        try:
            # 1. получаем временные метки чанков и массив аудио из канала агента
            raw_timeline, agent_audio = get_raw_timeline(
                model,
                file_path
                )
            # 2. объединяем чанки в цельные реплики (не более 1.2 секунд между ними)
            merged_timeline = merge_timeline(
                raw_timeline,
                1.2 # предельная длительность паузы, при которой чанки сливаются
                )
            # 3. получаем дорожку без пустот и словарь с транкрипцией и метриками
            agent_result_dict = process_merged_timeline(
                merged_timeline,
                agent_audio,
                text_embedder,

                ### OPENSMILE_PARSER, ###

                SPLITTER_MS=400 # длительность сплиттера в миллисекундах
                )
            # 4. дополняем словарь и формируем имя для нового аудиофайла
            new_dict = process_dict(
                agent_result_dict,
                file_path,
                )

            # 5. результаты в виде словаря -> список словарей
            agent_dicts.append(new_dict)

        # если не распозналось ни одной реплики, то упадет с ошибкой.
        # пропускаем такой файл, их не слишком много
        except Exception as e:
            # принт для отладки
            # print(f'Failed: {e} ({file_path})')
            continue

    # сложить словари в сводный датафрейм и отсортировать по хронологии
    agent_year_df = pd.DataFrame(agent_dicts)
    agent_year_df = agent_year_df.sort_values(
        ['agent_id', 'year', 'month', 'day', 'hour']
        ).reset_index(drop=True)

    # добавить датафрейм в словарь по сводному ID
    agent_years_df_dict[agent_year_id] = agent_year_df

# список для предсказаний по отдельным "оператор-год"
agent_years_df_predicted_list = []
agent_years_df_full_list = []

# 6. все предсказания
for agent_year_id, agent_year_df in agent_years_df_dict.items():
    agent_year_predicted_df, agent_year_df_full = predict_all(
        agent_year_df,
        json_string_filter,
        json_strings_experts,
        json_string_agent_sex,
        json_string_burnout
        )
    agent_years_df_predicted_list.append(agent_year_predicted_df)
    agent_years_df_full_list.append(agent_year_df_full)

# итоговый датафрейм
final_predictions_df = pd.concat(
    agent_years_df_predicted_list, axis=0
    )

# полный датафрейм для интерпретации
final_interpretation_df = pd.concat(
    agent_years_df_full_list, axis=0
    )

# сохранение в таблицу (xlsx)
final_predictions_df.to_excel('result.xlsx', index=False)
final_interpretation_df.to_excel('result_full.xlsx', index=False)

Detected Language: russian

Transcribe: 100%|██████████| 390.61/390.61 [00:05<00:00, 67.15sec/s]
Adjustment: 100%|██████████| 387.84/387.84 [00:00<00:00, 51489.85sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 379.73/379.73 [00:10<00:00, 35.92sec/s]
Adjustment: 100%|██████████| 379.63/379.63 [00:00<00:00, 34186.05sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 415.09/415.09 [00:11<00:00, 35.02sec/s]
Adjustment: 100%|██████████| 414.94/414.94 [00:00<00:00, 25419.69sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 339.27/339.27 [00:08<00:00, 41.32sec/s]
Adjustment: 100%|██████████| 338.42/338.42 [00:00<00:00, 30643.47sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 370.23/370.23 [00:10<00:00, 35.60sec/s]
Adjustment: 100%|██████████| 368.03/368.03 [00:00<00:00, 38049.49sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 392.69/392.69 [00:00<00:00, 751396.55sec/s]
Adjustment: 0sec [00:00, ?sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 338.12/338.12 [00:08<00:00, 42.04sec/s]
Adjustment: 100%|██████████| 335.98/335.98 [00:00<00:00, 12154.69sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 342.51/342.51 [00:01<00:00, 249.09sec/s]
Adjustment: 100%|██████████| 341.38/341.38 [00:00<00:00, 98145.97sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 360.44/360.44 [00:07<00:00, 46.70sec/s]
Adjustment: 100%|██████████| 360.22/360.22 [00:00<00:00, 40778.18sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 402.05/402.05 [00:10<00:00, 38.08sec/s]
Adjustment: 100%|██████████| 402.03/402.03 [00:00<00:00, 23049.87sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 315.37/315.37 [00:04<00:00, 74.87sec/s]
Adjustment: 100%|██████████| 315.34/315.34 [00:00<00:00, 110274.46sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 326.45/326.45 [00:02<00:00, 115.78sec/s]
Adjustment: 100%|██████████| 325.12/325.12 [00:00<00:00, 71994.73sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 377.21/377.21 [00:07<00:00, 52.58sec/s]
Adjustment: 100%|██████████| 377.08/377.08 [00:00<00:00, 129183.06sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 325.52/325.52 [00:06<00:00, 49.19sec/s]
Adjustment: 100%|██████████| 325.47/325.47 [00:00<00:00, 67297.02sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 333.8/333.8 [00:05<00:00, 62.74sec/s]
Adjustment: 100%|██████████| 333.76/333.76 [00:00<00:00, 119618.12sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 407.38/407.38 [00:08<00:00, 45.81sec/s]
Adjustment: 100%|██████████| 407.36/407.36 [00:00<00:00, 59793.23sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 327.17/327.17 [00:11<00:00, 28.64sec/s]
Adjustment: 100%|██████████| 327.09/327.09 [00:00<00:00, 76579.12sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 318.68/318.68 [00:06<00:00, 47.39sec/s]
Adjustment: 100%|██████████| 317.08/317.08 [00:00<00:00, 28122.86sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 301.61/301.61 [00:03<00:00, 97.74sec/s]
Adjustment: 100%|██████████| 301.02/301.02 [00:00<00:00, 49913.79sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 409.61/409.61 [00:05<00:00, 72.06sec/s]
Adjustment: 100%|██████████| 406.97/406.97 [00:00<00:00, 65348.03sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 354.39/354.39 [00:05<00:00, 68.64sec/s]
Adjustment: 100%|██████████| 347.65/347.65 [00:00<00:00, 38147.49sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 418.83/418.83 [00:04<00:00, 84.54sec/s]
Adjustment: 100%|██████████| 415.15/415.15 [00:00<00:00, 37185.86sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 329.98/329.98 [00:01<00:00, 245.91sec/s]
Adjustment: 100%|██████████| 328.16/328.16 [00:00<00:00, 144671.31sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 395.79/395.79 [00:08<00:00, 48.61sec/s]
Adjustment: 100%|██████████| 395.7/395.7 [00:00<00:00, 36233.73sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 380.6/380.6 [00:02<00:00, 127.16sec/s]
Adjustment: 100%|██████████| 376.88/376.88 [00:00<00:00, 60706.99sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 342.44/342.44 [00:02<00:00, 154.84sec/s]
Adjustment: 100%|██████████| 339.88/339.88 [00:00<00:00, 68309.94sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 331.28/331.28 [00:08<00:00, 37.79sec/s]
Adjustment: 100%|██████████| 331.23/331.23 [00:00<00:00, 56779.44sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 325.73/325.73 [00:01<00:00, 165.56sec/s]
Adjustment: 100%|██████████| 318.35/318.35 [00:00<00:00, 93407.25sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 332.0/332.0 [00:05<00:00, 64.67sec/s]
Adjustment: 100%|██████████| 329.91/329.91 [00:00<00:00, 26246.52sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 368.93/368.93 [00:05<00:00, 71.99sec/s]
Adjustment: 100%|██████████| 365.5/365.5 [00:00<00:00, 52423.42sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 334.16/334.16 [00:05<00:00, 63.51sec/s]
Adjustment: 100%|██████████| 332.36/332.36 [00:00<00:00, 34096.93sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 306.8/306.8 [00:02<00:00, 112.38sec/s]
Adjustment: 100%|██████████| 303.92/303.92 [00:00<00:00, 52538.14sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 320.62/320.62 [00:02<00:00, 132.41sec/s]
Adjustment: 100%|██████████| 318.09/318.09 [00:00<00:00, 87075.20sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 398.24/398.24 [00:06<00:00, 64.46sec/s]
Adjustment: 100%|██████████| 398.21/398.21 [00:00<00:00, 76706.80sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 414.15/414.15 [00:03<00:00, 126.46sec/s]
Adjustment: 100%|██████████| 414.13/414.13 [00:00<00:00, 31496.26sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 395.5/395.5 [00:01<00:00, 278.86sec/s]
Adjustment: 100%|██████████| 394.8/394.8 [00:00<00:00, 148166.72sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 358.64/358.64 [00:03<00:00, 105.02sec/s]
Adjustment: 100%|██████████| 356.52/356.52 [00:00<00:00, 101057.87sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 389.89/389.89 [00:01<00:00, 266.26sec/s]
Adjustment: 100%|██████████| 389.15/389.15 [00:00<00:00, 144905.31sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 327.75/327.75 [00:01<00:00, 235.37sec/s]
Adjustment: 100%|██████████| 326.81/326.81 [00:00<00:00, 56801.78sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 389.6/389.6 [00:02<00:00, 164.44sec/s]
Adjustment: 100%|██████████| 386.65/386.65 [00:00<00:00, 92337.74sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 319.11/319.11 [00:01<00:00, 252.79sec/s]
Adjustment: 100%|██████████| 317.44/317.44 [00:00<00:00, 119755.34sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 360.58/360.58 [00:03<00:00, 108.56sec/s]
Adjustment: 100%|██████████| 358.06/358.06 [00:00<00:00, 55960.52sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 303.85/303.85 [00:01<00:00, 222.78sec/s]
Adjustment: 100%|██████████| 302.81/302.81 [00:00<00:00, 38098.13sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 406.88/406.88 [00:03<00:00, 109.46sec/s]
Adjustment: 100%|██████████| 400.28/400.28 [00:00<00:00, 50763.34sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 349.06/349.06 [00:05<00:00, 58.22sec/s]
Adjustment: 100%|██████████| 349.03/349.03 [00:00<00:00, 53900.51sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 393.7/393.7 [00:04<00:00, 85.19sec/s]
Adjustment: 100%|██████████| 389.85/389.85 [00:00<00:00, 52932.87sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 418.97/418.97 [00:01<00:00, 276.19sec/s]
Adjustment: 100%|██████████| 416.01/416.01 [00:00<00:00, 113620.66sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 323.72/323.72 [00:01<00:00, 196.55sec/s]
Adjustment: 100%|██████████| 320.82/320.82 [00:00<00:00, 40750.33sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 302.19/302.19 [00:05<00:00, 58.00sec/s]
Adjustment: 100%|██████████| 298.67/298.67 [00:00<00:00, 66559.31sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 312.7/312.7 [00:04<00:00, 70.70sec/s]
Adjustment: 100%|██████████| 310.74/310.74 [00:00<00:00, 34387.96sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 418.9/418.9 [00:07<00:00, 55.86sec/s]
Adjustment: 100%|██████████| 415.2/415.2 [00:00<00:00, 42648.72sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 373.83/373.83 [00:02<00:00, 143.99sec/s]
Adjustment: 100%|██████████| 372.59/372.59 [00:00<00:00, 48480.09sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 312.63/312.63 [00:00<00:00, 622.03sec/s]
Adjustment: 100%|██████████| 310.34/310.34 [00:00<00:00, 171655.06sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 312.27/312.27 [00:01<00:00, 204.70sec/s]
Adjustment: 100%|██████████| 311.64/311.64 [00:00<00:00, 91246.97sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 336.32/336.32 [00:03<00:00, 87.94sec/s]
Adjustment: 100%|██████████| 326.0/326.0 [00:00<00:00, 61675.38sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 363.82/363.82 [00:05<00:00, 63.24sec/s]
Adjustment: 100%|██████████| 362.15/362.15 [00:00<00:00, 73006.21sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 330.41/330.41 [00:05<00:00, 61.11sec/s]
Adjustment: 100%|██████████| 328.65/328.65 [00:00<00:00, 85661.07sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 404.79/404.79 [00:06<00:00, 63.03sec/s]
Adjustment: 100%|██████████| 402.4/402.4 [00:00<00:00, 110457.33sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 387.08/387.08 [00:03<00:00, 96.83sec/s]
Adjustment: 100%|██████████| 386.82/386.82 [00:00<00:00, 39453.36sec/s]

Detected Language: russian

Transcribe: 100%|██████████| 418.33/418.33 [00:05<00:00, 73.71sec/s]
Adjustment: 100%|██████████| 418.3/418.3 [00:00<00:00, 82540.34sec/s]

## Substantiating

#### Making JSONs from txts

In [154]:
my_dict = {}

json_txt_path = '/content/json_string_burnout.txt'
json_name_txt = json_txt_path.rsplit('/', 1)[-1]

with open(json_name_txt, 'r') as f:
    for line in f.readlines():
        feature, weight = line.replace(',', '.').split()
        my_dict[feature] = float(weight)

json_name = json_name_txt[:-3] + "json"

# 1. Write the dictionary to a file
with open(json_name, "w") as f:
    json.dump(my_dict, f, indent=4)

### Feature blocks

In [26]:
acoustic_block_list = '''
ACOUSTIC_F0final_sma_max ACOUSTIC_F0final_sma_mean ACOUSTIC_F0final_sma_min ACOUSTIC_F0final_sma_std ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_max ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_mean	ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_min
ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_std	ACOUSTIC_F1bandwidth_sma3nz_max	ACOUSTIC_F1bandwidth_sma3nz_mean ACOUSTIC_F1bandwidth_sma3nz_min	ACOUSTIC_F1bandwidth_sma3nz_std
ACOUSTIC_F1frequency_sma3nz_max	ACOUSTIC_F1frequency_sma3nz_mean	ACOUSTIC_F1frequency_sma3nz_min	ACOUSTIC_F1frequency_sma3nz_std	ACOUSTIC_F2bandwidth_sma3nz_max	ACOUSTIC_F2bandwidth_sma3nz_mean	ACOUSTIC_F2bandwidth_sma3nz_min
ACOUSTIC_F2bandwidth_sma3nz_std	ACOUSTIC_F2frequency_sma3nz_max	ACOUSTIC_F2frequency_sma3nz_mean	ACOUSTIC_F2frequency_sma3nz_min	ACOUSTIC_F2frequency_sma3nz_std	ACOUSTIC_F3bandwidth_sma3nz_max	ACOUSTIC_F3bandwidth_sma3nz_mean
ACOUSTIC_F3bandwidth_sma3nz_min	ACOUSTIC_F3bandwidth_sma3nz_std	ACOUSTIC_F3frequency_sma3nz_max	ACOUSTIC_F3frequency_sma3nz_mean	ACOUSTIC_F3frequency_sma3nz_min	ACOUSTIC_F3frequency_sma3nz_std	ACOUSTIC_HNRdBACF_sma3nz_max
ACOUSTIC_HNRdBACF_sma3nz_mean	ACOUSTIC_HNRdBACF_sma3nz_min	ACOUSTIC_HNRdBACF_sma3nz_std	ACOUSTIC_audspec_lengthL1norm_sma_max	ACOUSTIC_audspec_lengthL1norm_sma_mean	ACOUSTIC_audspec_lengthL1norm_sma_min	ACOUSTIC_audspec_lengthL1norm_sma_std
ACOUSTIC_jitterDDP_sma_max	ACOUSTIC_jitterDDP_sma_mean		ACOUSTIC_jitterDDP_sma_std	ACOUSTIC_jitterLocal_sma3nz_max	ACOUSTIC_jitterLocal_sma3nz_mean		ACOUSTIC_jitterLocal_sma3nz_std
ACOUSTIC_jitterLocal_sma_max	ACOUSTIC_jitterLocal_sma_mean		ACOUSTIC_jitterLocal_sma_std	ACOUSTIC_logHNR_sma_max	ACOUSTIC_logHNR_sma_mean	ACOUSTIC_logHNR_sma_min	ACOUSTIC_logHNR_sma_std	ACOUSTIC_logRelF0_H1_A3_sma3nz_max
ACOUSTIC_logRelF0_H1_A3_sma3nz_mean	ACOUSTIC_logRelF0_H1_A3_sma3nz_min	ACOUSTIC_logRelF0_H1_A3_sma3nz_std	ACOUSTIC_logRelF0_H1_H2_sma3nz_max	ACOUSTIC_logRelF0_H1_H2_sma3nz_mean	ACOUSTIC_logRelF0_H1_H2_sma3nz_min	ACOUSTIC_logRelF0_H1_H2_sma3nz_std
ACOUSTIC_mfcc1_sma3_max	ACOUSTIC_mfcc1_sma3_mean	ACOUSTIC_mfcc1_sma3_min	ACOUSTIC_mfcc1_sma3_std	ACOUSTIC_mfcc2_sma3_max	ACOUSTIC_mfcc2_sma3_mean	ACOUSTIC_mfcc2_sma3_min	ACOUSTIC_mfcc2_sma3_std	ACOUSTIC_mfcc3_sma3_max	ACOUSTIC_mfcc3_sma3_mean
ACOUSTIC_mfcc3_sma3_min	ACOUSTIC_mfcc3_sma3_std	ACOUSTIC_mfcc4_sma3_max	ACOUSTIC_mfcc4_sma3_mean	ACOUSTIC_mfcc4_sma3_min	ACOUSTIC_mfcc4_sma3_std	ACOUSTIC_mfcc_sma_10_max	ACOUSTIC_mfcc_sma_10_mean	ACOUSTIC_mfcc_sma_10_min	ACOUSTIC_mfcc_sma_10_std
ACOUSTIC_mfcc_sma_11_max	ACOUSTIC_mfcc_sma_11_mean	ACOUSTIC_mfcc_sma_11_min	ACOUSTIC_mfcc_sma_11_std	ACOUSTIC_mfcc_sma_12_max	ACOUSTIC_mfcc_sma_12_mean	ACOUSTIC_mfcc_sma_12_min	ACOUSTIC_mfcc_sma_12_std	ACOUSTIC_mfcc_sma_13_max
ACOUSTIC_mfcc_sma_13_mean	ACOUSTIC_mfcc_sma_13_min	ACOUSTIC_mfcc_sma_13_std	ACOUSTIC_mfcc_sma_14_max	ACOUSTIC_mfcc_sma_14_mean	ACOUSTIC_mfcc_sma_14_min	ACOUSTIC_mfcc_sma_14_std	ACOUSTIC_mfcc_sma_1_max	ACOUSTIC_mfcc_sma_1_mean
ACOUSTIC_mfcc_sma_1_min	ACOUSTIC_mfcc_sma_1_std	ACOUSTIC_mfcc_sma_2_max	ACOUSTIC_mfcc_sma_2_mean	ACOUSTIC_mfcc_sma_2_min	ACOUSTIC_mfcc_sma_2_std	ACOUSTIC_mfcc_sma_3_max	ACOUSTIC_mfcc_sma_3_mean	ACOUSTIC_mfcc_sma_3_min	ACOUSTIC_mfcc_sma_3_std
ACOUSTIC_mfcc_sma_4_max	ACOUSTIC_mfcc_sma_4_mean	ACOUSTIC_mfcc_sma_4_min	ACOUSTIC_mfcc_sma_4_std	ACOUSTIC_mfcc_sma_5_max	ACOUSTIC_mfcc_sma_5_mean	ACOUSTIC_mfcc_sma_5_min	ACOUSTIC_mfcc_sma_5_std	ACOUSTIC_mfcc_sma_6_max	ACOUSTIC_mfcc_sma_6_mean
ACOUSTIC_mfcc_sma_6_min	ACOUSTIC_mfcc_sma_6_std	ACOUSTIC_mfcc_sma_7_max	ACOUSTIC_mfcc_sma_7_mean	ACOUSTIC_mfcc_sma_7_min	ACOUSTIC_mfcc_sma_7_std	ACOUSTIC_mfcc_sma_8_max	ACOUSTIC_mfcc_sma_8_mean	ACOUSTIC_mfcc_sma_8_min	ACOUSTIC_mfcc_sma_8_std
ACOUSTIC_mfcc_sma_9_max	ACOUSTIC_mfcc_sma_9_mean	ACOUSTIC_mfcc_sma_9_min	ACOUSTIC_mfcc_sma_9_std	ACOUSTIC_pcm_RMSenergy_sma_max	ACOUSTIC_pcm_RMSenergy_sma_mean		ACOUSTIC_pcm_RMSenergy_sma_std
ACOUSTIC_pcm_fftMag_psySharpness_sma_max	ACOUSTIC_pcm_fftMag_psySharpness_sma_mean	ACOUSTIC_pcm_fftMag_psySharpness_sma_min	ACOUSTIC_pcm_fftMag_psySharpness_sma_std	ACOUSTIC_pcm_fftMag_spectralHarmonicity_sma_max
ACOUSTIC_pcm_fftMag_spectralHarmonicity_sma_mean		ACOUSTIC_pcm_fftMag_spectralHarmonicity_sma_std	ACOUSTIC_shimmerLocal_sma_max	ACOUSTIC_shimmerLocal_sma_mean	ACOUSTIC_shimmerLocal_sma_min
ACOUSTIC_shimmerLocal_sma_std	ACOUSTIC_shimmerLocaldB_sma3nz_max	ACOUSTIC_shimmerLocaldB_sma3nz_mean		ACOUSTIC_shimmerLocaldB_sma3nz_std'''.split()

asr_block_list = ['word_count', 'avg_interword_pause_ms', 'std_interword_pause_ms', 'avg_speech_rate_wps', 'std_speech_rate_wps', 'acc_speech_rate_wps', 'duration_sec', 'rms_energy']

emo_block_list = '''	EMO_Diminutive	EMO_Ethical	EMO_ExpressLex	EMO_General	EMO_Hyperbole	EMO_LoweredLex	EMO_Pragmatic	EMO_Rational	EMO_Sentimental	'''.split()

lex_block_list = '''LEX_Antithesis		LEX_Antonyms LEX_Attitude		LEX_Comparisons	LEX_EmotLex	LEX_IntelLex	LEX_MultiComp
LEX_Overlex				LEX_SynChain	LEX_SynRows34	LEX_TempLex	LEX_Tropes	LEX_Underlex 	LEX_WorkSyn'''.split()

mor_block_list = '''MOR_ActiveFreq	MOR_AdvMPC MOR_CoordConj	MOR_CoordDomin	MOR_GenderErr	MOR_ImperFreq	MOR_IntensPart	MOR_LimitPart	MOR_ModalFreq	MOR_PassiveFreq	MOR_RelPronConj	MOR_StateWords	MOR_SubordConj	MOR_SubordDomin'''.split()

ortpun_block_list = '''	ORT_AltRootVow		 	ORT_NotErr		ORT_TakZheErr
PUN_CommaDetach		PUN_Dash	PUN_EmoMarks	PUN_HomogErr		PUN_Quotes'''.split()

strsyn_block_list = '''STR_Argum	STR_Chaotic		STR_Coher	STR_Concise	STR_ConjLinks	STR_Deductive	STR_Digress
STR_EmClaim	STR_Inductive			STR_LogLink		STR_NoLogic	STR_SSC_Coherent SYN_AdjectPh	SYN_AsyndetFreq	SYN_ChtobyPref	SYN_ComplexSent	SYN_ConjFreq	SYN_ElipSent
SYN_HighSpread SYN_MixConst	SYN_NominalPh	SYN_Sogl	SYN_SoglDomin	SYN_Upravl	SYN_UpravlDomin	SYN_VerbalPh'''.split()

In [27]:
expert_block = ('Психолингвистика', list(json_strings_experts.keys()))

asr_block = ('Речевые характеристики', asr_block_list)

bert_block = ('Эмбеддинги BERT', [f'bert_{i + 1}' for i in range(1024)]) # хардкодом для скорости

acoustic_block = ('Акустика', acoustic_block_list)

emo_block = ('Эмоции и экспрессия', emo_block_list)
lex_block = ('Лексика и семантика', lex_block_list)

mor_block = ('Морфология', mor_block_list)
ortpun_block = ('Орфография и пунктуация', ortpun_block_list)

strsyn_block = ('Синтаксис', strsyn_block_list)

### Calculating importances

In [28]:
# подсчет вклада признаков
def calculate_block_importances(row: pd.Series,
                                block: list,
                                top_n: int = 3
                                ) -> pd.Series:

    # весовые коэффициенты для блока признаков
    block_weights = pd.Series({k: v for k, v in json_string_burnout.items() if k in block})
    # значения в блоке
    block_values = row[block]

    # итоговый вклад в оценку
    block_importances = (block_weights * block_values).\
                        sort_values(ascending=False, key=abs).\
                        head(top_n)

    # вернуть серию pandas
    return block_importances

### Interpretation loop

In [32]:
final_predictions_df

                              file_name   burnout  burnout_final
0   20230904103009_Оператор12_muted.wav -1.610026              0
1   20230927125324_Оператор12_muted.wav -1.610026              0
2   20230927140858_Оператор12_muted.wav -1.610026              0
3   20230927150013_Оператор12_muted.wav -1.610026              0
4   20230928172132_Оператор12_muted.wav -1.610026              0
5   20230928173608_Оператор12_muted.wav -1.610026              0
6   20231006113013_Оператор12_muted.wav -1.610026              0
7   20231019160503_Оператор12_muted.wav -1.610026              0
8   20231019164521_Оператор12_muted.wav -1.610026              0
9   20231023092551_Оператор12_muted.wav -1.610026              0
10  20231030095819_Оператор12_muted.wav -1.610026              0
11  20231030110201_Оператор12_muted.wav -1.610026              0
12        20231030162610_Оператор12.wav -1.610026              0
13  20231108092022_Оператор12_muted.wav -1.610026              0
0   20230929111051_Оператор13_muted.wav -1.587210              0
1   20230929122901_Оператор13_muted.wav -1.587210              0
2   20231017171429_Оператор13_muted.wav -1.587210              0
3   20231018095210_Оператор13_muted.wav -1.587210              0
4   20231023085053_Оператор13_muted.wav -1.587210              0
5   20231023090239_Оператор13_muted.wav -1.587210              0
6   20231024091413_Оператор13_muted.wav -1.587210              0
7   20231024134156_Оператор13_muted.wav -1.587210              0
8   20231031091532_Оператор13_muted.wav -1.587210              0
9   20231122113755_Оператор13_muted.wav -1.587210              0
10  20231122164410_Оператор13_muted.wav -1.587210              0
11  20231207154310_Оператор13_muted.wav -1.587210              0
12  20231211104602_Оператор13_muted.wav -1.587210              0
13  20231214123255_Оператор13_muted.wav -1.587210              0
14  20231214173656_Оператор13_muted.wav -1.587210              0
0   20240801100418_Оператор15_muted.wav -1.698472              0
1   20240801125822_Оператор15_muted.wav -1.698472              0
2   20240801160818_Оператор15_muted.wav -1.698472              0
3   20240827114621_Оператор15_muted.wav -1.698472              0
4   20240827161046_Оператор15_muted.wav -1.698472              0
5   20240909125817_Оператор15_muted.wav -1.698472              0
6   20240909131947_Оператор15_muted.wav -1.698472              0
7   20240910150220_Оператор15_muted.wav -1.698472              0
8   20240911113515_Оператор15_muted.wav -1.698472              0
9   20241102082716_Оператор15_muted.wav -1.698472              0
10  20241102084837_Оператор15_muted.wav -1.698472              0
11  20241102144157_Оператор15_muted.wav -1.698472              0
12  20241105061358_Оператор15_muted.wav -1.698472              0
13  20241118130123_Оператор15_muted.wav -1.698472              0
14  20241118162438_Оператор15_muted.wav -1.698472              0
0   20230904165059_Оператор14_muted.wav -1.452556              0
1   20230905112650_Оператор14_muted.wav -1.452556              0
2   20230905164056_Оператор14_muted.wav -1.452556              0
3   20230906162409_Оператор14_muted.wav -1.452556              0
4   20231006140821_Оператор14_muted.wav -1.452556              0
5   20231006142603_Оператор14_muted.wav -1.452556              0
6   20231009161042_Оператор14_muted.wav -1.452556              0
7   20231009162032_Оператор14_muted.wav -1.452556              0
8   20231102133935_Оператор14_muted.wav -1.452556              0
9   20231102145031_Оператор14_muted.wav -1.452556              0
10  20231103102110_Оператор14_muted.wav -1.452556              0
11  20231207072504_Оператор14_muted.wav -1.452556              0
12  20231208122309_Оператор14_muted.wav -1.452556              0
13  20231225101126_Оператор14_muted.wav -1.452556              0
14  20231225115301_Оператор14_muted.wav -1.452556              0

In [31]:
final_interpretation_df = pd.read_excel('/content/result_full.xlsx')
final_interpretation_df

,file_name,agent_id,year,month,day,weekday,hour,text,word_count,avg_interword_pause_ms,...,farewell_flg,etiquette_present_flg,etiquette_absent_flg,participation_dominant_flg,distancing_dominant_flg,clarifying_absent_flg,m,f,burnout,burnout_final
0,20230904103009_Оператор12_muted.wav,_12,2023,9,4,Mon,10,Служба поддержки пользователей. Меня зовут Ана...,135,196,...,2.141660,1.949329,-0.949329,0.924801,0.057381,0.305739,1,0,-1.610026,0
1,20230927125324_Оператор12_muted.wav,_12,2023,9,27,Wed,12,"Служба поддержки пользователей, меня зовут Ана...",175,170,...,2.014764,1.753135,-0.753135,0.983027,0.006853,0.294120,1,0,-1.610026,0
2,20230927140858_Оператор12_muted.wav,_12,2023,9,27,Wed,14,Служба поддержки пользователей. Меня зовут Ана...,215,156,...,1.926226,1.760999,-0.760999,1.065340,-0.054354,0.150995,1,0,-1.610026,0
3,20230927150013_Оператор12_muted.wav,_12,2023,9,27,Wed,15,"Меня зовут Анастасия, добрый день. | К вам мог...",127,206,...,1.907264,1.649685,-0.649685,1.002892,-0.009662,0.270213,1,0,-1.610026,0
4,20230928172132_Оператор12_muted.wav,_12,2023,9,28,Thu,17,Служба поддержки пользователей. Меня зовут Ана...,268,280,...,2.064168,1.827915,-0.827915,1.081591,-0.063711,-0.005980,1,0,-1.610026,0
5,20230928173608_Оператор12_muted.wav,_12,2023,9,28,Thu,17,"Служба поддержки пользователей, меня зовут Ана...",277,234,...,1.915535,1.737694,-0.737694,0.904682,0.076116,0.161677,1,0,-1.610026,0
6,20231006113013_Оператор12_muted.wav,_12,2023,10,6,Fri,11,Служба поддержки пользователей. Меня зовут Ана...,72,173,...,2.099180,2.056094,-1.056094,0.931588,0.052649,0.411199,1,0,-1.610026,0
7,20231019160503_Оператор12_muted.wav,_12,2023,10,19,Thu,16,Служба поддержки пользователей. Меня зовут Ана...,390,220,...,2.085982,1.836418,-0.836418,0.992358,0.005826,0.104174,1,0,-1.610026,0
8,20231019164521_Оператор12_muted.wav,_12,2023,10,19,Thu,16,Служба поддержки пользователей. Меня зовут Ана...,139,192,...,1.902419,1.668687,-0.668687,1.011532,-0.014748,0.224346,1,0,-1.610026,0
9,20231023092551_Оператор12_muted.wav,_12,2023,10,23,Mon,9,"Служба поддержки пользователей, меня зовут Ана...",191,267,...,2.195646,1.978086,-0.978086,1.085726,-0.072233,0.235727,1,0,-1.610026,0
10,20231030095819_Оператор12_muted.wav,_12,2023,10,30,Mon,9,"Служба поддержки пользователей, меня зовут Ана...",299,215,...,2.077169,1.903942,-0.903942,1.027529,-0.019401,0.056300,1,0,-1.610026,0
11,20231030110201_Оператор12_muted.wav,_12,2023,10,30,Mon,11,Служба поддержки пользователей. Меня зовут Ана...,118,214,...,2.052538,1.870175,-0.870175,1.255286,-0.206686,0.080326,1,0,-1.610026,0
12,20231030162610_Оператор12.wav,_12,2023,10,30,Mon,16,Служба поддержки пользователей. Меня зовут Ана...,238,212,...,1.862513,1.667009,-0.667009,0.936958,0.045233,0.280809,1,0,-1.610026,0
13,20231108092022_Оператор12_muted.wav,_12,2023,11,8,Wed,9,Служба поддержки пользователей. Меня зовут Ана...,356,260,...,1.875567,1.651010,-0.651010,0.936122,0.048885,0.154378,1,0,-1.610026,0
14,20230929111051_Оператор13_muted.wav,_13,2023,9,29,Fri,11,"Здравствуйте, Никита. | Назовите мне полностью...",94,162,...,1.854189,1.756483,-0.756483,1.044577,-0.039262,0.257196,1,0,-1.587210,0
15,20230929122901_Оператор13_muted.wav,_13,2023,9,29,Fri,12,"Раз, скажу, подержки, кажется, у меня зовут не...",162,234,...,1.572982,1.474646,-0.474646,1.191109,-0.157573,0.109620,1,0,-1.587210,0
16,20231017171429_Оператор13_muted.wav,_13,2023,10,17,Tue,17,"Назвучите, да? | Да, зовите меня полностью, у ...",207,204,...,1.884124,1.583447,-0.583447,1.327133,-0.267512,-0.023130,1,0,-1.587210,0
17,20231018095210_Оператор13_muted.wav,_13,2023,10,18,Wed,9,"Какую вы заявку делали? Подскажите, пожалуйста...",249,338,...,1.827144,1.504871,-0.504871,1.053699,-0.050740,0.163011,1,0,-1.587210,0
18,20231023085053_Оператор13_muted.wav,_13,2023,10,23,Mon,8,"Ваши фамилии, имя, отчества? | Подскажите, пож...",252,232,...,1.924989,1.642306,-0.642306,1.123625,-0.103012,0.069669,1,0,-1.587210,0
19,20231023090239_Оператор13_muted.wav,_13,2023,10,23,Mon,9,"Здравствуйте, Пустина, зовут Никита. | Что вам...",291,246,...,1.871944,1.769302,-0.769302,1.159030,-0.124606,-0.022263,1,0,-1.587210,0
20,20231024091413_Оператор13_muted.wav,_13,2023,10,24,Tue,9,"Здравствуйте, поддержки постельно зовут, да? |...",96,166,...,1.973588,1.906158,-0.906158,1.064589,-0.047848,0.062101,1,0,-1.587210,0
21,20231024134156_Оператор13_muted.wav,_13,2023,10,24,Tue,13,"Здравствуйте, уже поддержки профессиональные, ...",238,243,...,2.019182,1.744346,-0.744346,1.240898,-0.195701,0.003206,1,0,-1.587210,0
22,20231031091532_Оператор13_muted.wav,_13,2023,10,31,Tue,9,"Здравствуйте. Уже поездки костюма, заработники...",285,230,...,1.897821,1.626272,-0.626272,1.047567,-0.042108,0.113609,1,0,-1.587210,0
23,20231122113755_Оператор13_muted.wav,_13,2023,11,22,Wed,11,Здравствуйте! Меня зовут Никита. | Назовете мн...,214,264,...,1.872916,1.616912,-0.616912,1.185942,-0.153279,0.055730,1,0,-1.587210,0
24,20231122164410_Оператор13_muted.wav,_13,2023,11,22,Wed,16,Какую папку? Куда выображаете документы? | Пон...,257,255,...,2.025801,1.679328,-0.679328,1.317065,-0.256623,-0.110527,1,0,-1.587210,0
25,20231207154310_Оператор13_muted.wav,_13,2023,12,7,Thu,15,"Здравствуйте, уже в поддержке. Простите меня, ...",233,194,...,1.614700,1.497549,-0.497549,1.021928,-0.018762,0.085101,1,0,-1.587210,0
26,20231211104602_Оператор13_muted.wav,_13,2023,12,11,Mon,10,"Да, я вижу ваш рабочий стол, а у вас, получает...",143,224,...,1.613584,1.386982,-0.386982,1.250459,-0.205372,-0.027283,1,0,-1.587210,0
27,20231214123255_Оператор13_muted.wav,_13,2023,12,14,Thu,12,"Поддержки профессионалов, заводник. | Скажите ...",146,182,...,1.721932,1.487608,-0.487608,0.950421,0.031361,0.291718,1,0,-1.587210,0
28,20231214173656_Оператор13_muted.wav,_13,2023,12,14,Thu,17,"Здравствуйте, Кита. | Назовите мне полностью с...",176,225,...,2.193138,1.768230,-0.768230,1.239501,-0.198425,0.048124,1,0,-1.587210,0
29,20240801100418_Оператор15_muted.wav,_15,2024,8,1,Thu,10,"Служба поддержки пользователей. Юлия, здравств...",86,254,...,2.118256,1.936894,-0.936894,0.983481,0.008876,0.327858,0,1,-1.698472,0
30,20240801125822_Оператор15_muted.wav,_15,2024,8,1,Thu,12,"Поддержка пользователя Юлия, здравствуйте. | А...",98,161,...,2.083567,1.929630,-0.929630,1.007536,-0.011119,0.354725,0,1,-1.698472,0
31,20240801160818_Оператор15_muted.wav,_15,2024,8,1,Thu,16,"Вы не могли бы еще раз повторить фамилию, имя,...",139,254,...,1.864744,1.649849,-0.649849,1.001548,-0.009017,0.313290,0,1,-1.698472,0
32,20240827114621_Оператор15_muted.wav,_15,2024,8,27,Tue,11,"Служба поддержки пользователей Юлия, здравству...",76,279,...,2.084436,1.942439,-0.942439,1.012265,-0.015780,0.394324,0,1,-1.698472,0
33,20240827161046_Оператор15_muted.wav,_15,2024,8,27,Tue,16,"Служба поддержки пользователей Юрия, здравству...",118,192,...,2.147051,2.031530,-1.031530,1.004607,-0.003962,0.251314,0,1,-1.698472,0
34,20240909125817_Оператор15_muted.wav,_15,2024,9,9,Mon,12,"Служба поддержки пользователей Юлия, здравству...",137,159,...,2.108542,1.899391,-0.899391,1.067010,-0.059113,0.288172,0,1,-1.698472,0
35,20240909131947_Оператор15_muted.wav,_15,2024,9,9,Mon,13,Поддержки пользователей Юлия. Здравствуйте. | ...,124,247,...,2.100176,1.861162,-0.861162,1.052020,-0.047201,0.267050,0,1,-1.698472,0
36,20240910150220_Оператор15_muted.wav,_15,2024,9,10,Tue,15,А могли бы уточнить номер вашего обращения? | ...,147,306,...,1.849409,1.532449,-0.532449,1.143038,-0.125988,0.253874,0,1,-1.698472,0
37,20240911113515_Оператор15_muted.wav,_15,2024,9,11,Wed,11,"Служба поддержки пользователей Юлия, здравству...",168,158,...,2.049628,1.854331,-0.854331,1.034762,-0.032425,0.269446,0,1,-1.698472,0
38,20241102082716_Оператор15_muted.wav,_15,2024,11,2,Sat,8,"Номер обращения, по которому выполнялись работ...",73,264,...,1.981686,1.748950,-0.748950,1.107130,-0.094466,0.308802,0,1,-1.698472,0
39,20241102084837_Оператор15_muted.wav,_15,2024,11,2,Sat,8,"Служба поддержки пользователей Юлия, здравству...",177,133,...,1.923160,1.772808,-0.772808,0.903730,0.074622,0.269799,0,1,-1.698472,0
40,20241102144157_Оператор15_muted.wav,_15,2024,11,2,Sat,14,"Служба поддержки пользователей Юрьевна, здравс...",220,207,...,1.983808,1.787023,-0.787023,0.973873,0.017073,0.253358,0,1,-1.698472,0
41,20241105061358_Оператор15_muted.wav,_15,2024,11,5,Tue,6,Сосуд поддержки пользователей Юлия Здравствуйт...,127,177,...,1.863114,1.675979,-0.675979,1.031194,-0.032644,0.319902,0,1,-1.698472,0
42,20241118130123_Оператор15_muted.wav,_15,2024,11,18,Mon,13,"Поддержки пользователей Юлия, здравствуйте. | ...",103,140,...,2.323825,2.070747,-1.070747,1.230526,-0.187759,0.150080,0,1,-1.698472,0
43,20241118162438_Оператор15_muted.wav,_15,2024,11,18,Mon,16,"Служба поддержки пользователей, Юлия, здравств...",179,661,...,1.896503,1.805167,-0.805167,1.018069,-0.016175,0.229155,0,1,-1.698472,0
44,20230904165059_Оператор14_muted.wav,_14,2023,9,4,Mon,16,Вопрос. | Какая ошибка именно выходит? Какая-т...,146,226,...,2.000163,1.811231,-0.811231,1.024947,-0.023238,0.218219,1,0,-1.452556,0
45,20230905112650_Оператор14_muted.wav,_14,2023,9,5,Tue,11,"Сотрудника также назвать, пожалуйста. | Вижу, ...",103,284,...,1.702902,1.473597,-0.473597,1.069178,-0.065805,0.295011,1,0,-1.452556,0
46,20230905164056_Оператор14_muted.wav,_14,2023,9,5,Tue,16,"Подскажите, одна на MAP2 не можете выйти, прав...",166,215,...,2.039031,1.714304,-0.714304,1.278035,-0.227802,0.021176,1,0,-1.452556,0
47,20230906162409_Оператор14_muted.wav,_14,2023,9,6,Wed,16,"Да, скажите номер. | Заявка сейчас на согласов...",80,195,...,2.160107,1.782892,-0.782892,1.151758,-0.133387,0.312531,1,0,-1.452556,0
48,20231006140821_Оператор14_muted.wav,_14,2023,10,6,Fri,14,"Скажите вашу фамилию. | Сейчас одна минута, ин...",115,422,...,1.828633,1.632037,-0.632037,1.223895,-0.183926,0.086835,1,0,-1.452556,0
49,20231006142603_Оператор14_muted.wav,_14,2023,10,6,Fri,14,Принтер можете настроить у нас. Нужно будет по...,222,306,...,1.713665,1.494618,-0.494618,1.006625,-0.010333,0.158696,1,0,-1.452556,0
50,20231009161042_Оператор14_muted.wav,_14,2023,10,9,Mon,16,"Добрый день, служба поддержки пользователей, Е...",237,241,...,2.089251,1.902049,-0.902049,1.165745,-0.129221,-0.059946,1,0,-1.452556,0
51,20231009162032_Оператор14_muted.wav,_14,2023,10,9,Mon,16,"Да, назовите, пожалуйста, фамилиями. | Давайте...",222,219,...,1.748292,1.402669,-0.402669,1.196389,-0.166944,0.099369,1,0,-1.452556,0
52,20231102133935_Оператор14_muted.wav,_14,2023,11,2,Thu,13,"Мы вчера делали заявочку, у меня не было допус...",183,300,...,1.833876,1.527445,-0.527445,1.167123,-0.141333,0.109836,1,0,-1.452556,0
53,20231102145031_Оператор14_muted.wav,_14,2023,11,2,Thu,14,Подскажите фамилию Меджин. | Заявка на доступ ...,254,234,...,1.637779,1.384136,-0.384136,1.002170,-0.007706,0.132492,1,0,-1.452556,0
54,20231103102110_Оператор14_muted.wav,_14,2023,11,3,Fri,10,"Добрый день, служба поддержки пользователей, Е...",194,211,...,2.036982,1.890253,-0.890253,0.876716,0.099997,0.199685,1,0,-1.452556,0
55,20231207072504_Оператор14_muted.wav,_14,2023,12,7,Thu,7,Добрый день. Служба поддержки позиции Викини. ...,20,140,...,2.111723,1.972305,-0.972305,1.241705,-0.206681,0.525314,1,0,-1.452556,0
56,20231208122309_Оператор14_muted.wav,_14,2023,12,8,Fri,12,"Добрый день! Служба поддержки пользователей, Е...",151,249,...,1.806252,1.685340,-0.685340,1.179980,-0.146736,0.109035,1,0,-1.452556,0
57,20231225101126_Оператор14_muted.wav,_14,2023,12,25,Mon,10,"Так, куда? На ноутбук? | На банковский? | Скаж...",146,313,...,1.767369,1.562157,-0.562157,1.045301,-0.038144,0.061056,1,0,-1.452556,0
58,20231225115301_Оператор14_muted.wav,_14,2023,12,25,Mon,11,"В мобильный офис не можете зайти, да? | Скорее...",131,213,...,2.092477,1.759844,-0.759844,1.138840,-0.117103,0.135945,1,0,-1.452556,0

In [30]:
for i, row in final_interpretation_df.iterrows():
    print('*'*50)
    agent_sex = 'M' if row['m'] == 1 else 'F'

    print(f'{i} Файл:', row['file_name'])

    burnout_confidence, burnout_binarized = row['burnout'], row['burnout_final']

    if burnout_confidence < 0.5:
        burnout_confidence = 1 - burnout_confidence

    burnout_mapper = {1: 'Да', 0: 'Нет'}
    print(f'Выгорание: {burnout_mapper.get(burnout_binarized, "Не определено")} (уверенность: {burnout_confidence})')

    print(
        'Пол:', agent_sex
        )

    print('\nВклад признаков:')

    for j, block_tuple in enumerate([
        asr_block,
        # bert_block, # не интерпретируемый
        acoustic_block,
        emo_block,
        lex_block,
        mor_block,
        ortpun_block,
        strsyn_block,
        expert_block
        ], 1):
      block_name, block = block_tuple
      print('*'*50)
      print(f'{j}. {block_name}')
      print()
      print(calculate_block_importances(row, block, 1))
      print()

**************************************************
0 Файл: 20230904103009_Оператор12_muted.wav
Выгорание: Нет (уверенность: 2.610026187933757)
Пол: M

Вклад признаков:
**************************************************
1. Речевые характеристики

std_speech_rate_wps   -0.022991
dtype: object

**************************************************
2. Акустика

KeyError: "None of [Index(['ACOUSTIC_F0final_sma_max', 'ACOUSTIC_F0final_sma_mean',\n       'ACOUSTIC_F0final_sma_min', 'ACOUSTIC_F0final_sma_std',\n       'ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_max',\n       'ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_mean',\n       'ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_min',\n       'ACOUSTIC_F0semitoneFrom27_5Hz_sma3nz_std',\n       'ACOUSTIC_F1bandwidth_sma3nz_max', 'ACOUSTIC_F1bandwidth_sma3nz_mean',\n       ...\n       'ACOUSTIC_pcm_fftMag_spectralHarmonicity_sma_max',\n       'ACOUSTIC_pcm_fftMag_spectralHarmonicity_sma_mean',\n       'ACOUSTIC_pcm_fftMag_spectralHarmonicity_sma_std',\n       'ACOUSTIC_shimmerLocal_sma_max', 'ACOUSTIC_shimmerLocal_sma_mean',\n       'ACOUSTIC_shimmerLocal_sma_min', 'ACOUSTIC_shimmerLocal_sma_std',\n       'ACOUSTIC_shimmerLocaldB_sma3nz_max',\n       'ACOUSTIC_shimmerLocaldB_sma3nz_mean',\n       'ACOUSTIC_shimmerLocaldB_sma3nz_std'],\n      dtype='object', length=150)] are in the [index]"